### ISSUE TITLE
not possible to press enter from repl

### ISSUE THREAD

**Issue by dch** [bgianfo/todr#1]
I'm new to rust so apologies for the vague bug report. On pressing the enter key, all I see is ^M each time so it's not possible to enter and commands. Maybe related to the repl crate?

```sh
No previous history to load...
>> h  ^M^M^M
```

Building from master, using rust 1.16.0, on FreeBSD 12.0-CURRENT amd64.

**Comment by bgianfo** [comment]
Sorry I just saw this bug.

I'm guessing you are right and it's related the crate used for repl.
Will try to repro on FreeBSD when I get a chance.

**Comment by bgianfo** [comment]
I believe this should be fixed by https://github.com/bgianfo/todr/commit/0f58759587d4c93928e6757c01f10e830821ecd2, where we updated to the latest rustyline, which claims support for freebsd.
